spring:
  data:
    redis:
      host: ${REDIS_HOST:redis-service}
      port: ${REDIS_PORT:6379}

gateway:
  ratelimit:
    default-capacity: 1000
    default-refill-rate: 100
    fail-open: true
  discovery:
    type: memory

logging:
  level:
    com.mo.gateway: DEBUG
    root: INFO